/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "main.h"
// USER END

#include "DIALOG.h"
//extern GRAPH_DATA_Handle aGraph_Data; // Array of handles for the GRAPH_DATA objects
GUI_COLOR aGraphColor = GUI_RED; // Array of colors for the GRAPH_DATA objects
DROPDOWN_Handle _hDropDownScale;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_EDIT_0  (GUI_ID_USER + 0x01)
#define ID_RADIO_0  (GUI_ID_USER + 0x02)
#define ID_BUTTON_0  (GUI_ID_USER + 0x03)
#define ID_BUTTON_1  (GUI_ID_USER + 0x04)
#define ID_BUTTON_2  (GUI_ID_USER + 0x05)
#define ID_TEXT_0  (GUI_ID_USER + 0x06)
#define ID_TEXT_1  (GUI_ID_USER + 0x07)
#define ID_BUTTON_3  (GUI_ID_USER + 0x08)
#define ID_TEXT_2  (GUI_ID_USER + 0x09)
#define ID_EDIT_1  (GUI_ID_USER + 0x0A)
#define ID_SLIDER_0  (GUI_ID_USER + 0x0B)
#define ID_GRAPH_0  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_4  (GUI_ID_USER + 0x0D)
#define ID_BUTTON_5  (GUI_ID_USER + 0x0E)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static int first = 1;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SDR_MainForm", ID_WINDOW_0, 2, 1, 319, 239, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Station", ID_EDIT_0, 95, 5, 216, 37, 0, 0x64, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 3, 5, 86, 98, 0, 0x1405, 0 },
  { BUTTON_CreateIndirect, "Mute", ID_BUTTON_0, 268, 73, 44, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "AM", ID_BUTTON_1, 94, 44, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Narrow", ID_BUTTON_2, 94, 73, 60, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "BW", ID_TEXT_0, 68, 80, 32, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "AGC", ID_TEXT_1, 166, 80, 35, 17, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Fast", ID_BUTTON_3, 200, 73, 60, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Freq", ID_TEXT_2, 169, 46, 138, 26, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Freq1", ID_EDIT_1, 171, 45, 138, 26, 0, 0x64, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 102, 102, 205, 20, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 57, 125, 256, 113, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Spectogram", ID_BUTTON_4, 4, 125, 51, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Scale", ID_BUTTON_5, 4, 155, 51, 25, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'SDR_MainForm'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00000000);
    //
    // Initialization of 'Station'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "F=123,456,780.7");
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x0000FF40);
    EDIT_SetFont(hItem, GUI_FONT_32B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetTextColor(hItem, 0x0080FFFF);
    RADIO_SetText(hItem, "100s kHz", 0);
    RADIO_SetText(hItem, "10s kHz", 1);
    RADIO_SetText(hItem, "kHz", 2);
    RADIO_SetText(hItem, "100s Hz", 3);
    RADIO_SetText(hItem, "10s Hz", 4);
    //
    // Initialization of 'Mute'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'AM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Narrow'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'BW'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, 0x0000FFFF);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'AGC'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextColor(hItem, 0x0000FFFF);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Fast'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Freq'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, 0x0000FFFF);
    TEXT_SetText(hItem, "12345678 Hz");
    //
    // Initialization of 'Freq1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_24B_ASCII);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x0000FFFF);
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    //
    // Initialization of 'Graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 0, 0, 0, 0);
    /* Add graphs */

    aGraph_Data = GRAPH_DATA_YT_Create(aGraphColor, BSIZE/2, 0, 0);
    GRAPH_AttachData(hItem, aGraph_Data);

    /*  Set graph attributes */

    GRAPH_SetGridDistY(hItem, 15);
    GRAPH_SetGridVis(hItem, 1);
    GRAPH_SetGridDistX(hItem, 10);
    GRAPH_SetGridFixedX(hItem, 1);

    //
    // Initialization of 'Spectogram'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "On/Off");
    //
    // Initialization of 'Scale'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "Scale");
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);

    // USER START (Optionally insert additional code for further widget initialization)
      hItem = WM_GetDialogItem(pMsg->hWin, hSTATION);
      EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_BLACK);
      hItem = WM_GetDialogItem(pMsg->hWin, hFREQ);
      EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_BLACK);
			EDIT_SetFocussable(hItem, false);
			
			hItem = WM_GetDialogItem(pMsg->hWin, hVOL);
			SLIDER_SetRange(hItem, 0, 100);
//--------------------- Initializations -----------------------------------			
			if(first)
			{
        first = false;
        GlobalMsgPtr = pMsg;
			  hItem = WM_GetDialogItem(pMsg->hWin, hVOL);
			  SLIDER_SetValue(hItem, 25);   // initial default volume level
			}	
//--------------------------------------------------------------------------
			Fstep = 100000;
		    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Station'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
			  hItem = WM_GetDialogItem(pMsg->hWin, hFRADIO);
        SetFstep(RADIO_GetValue(hItem));
			        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Mute'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(bouncing()) break;
			     if(Muted)
					 {
             volume = oldvol;
             Muted = false;
						 ChangeColor(pMsg->hWin, hMUTE, GUI_BLACK);
			     }
					 else
					 {
						 oldvol = volume;	 
						 volume = 0.f;
						 Muted = true;
						 ChangeColor(pMsg->hWin, hMUTE, GUI_RED);
					 }	 
			        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'AM'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetMode(pMsg->hWin, AM);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Narrow'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetBW(pMsg->hWin, Narrow);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Fast'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetAGC(pMsg->hWin, Fast);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Freq1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Spectogram'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Scale'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSDR_MainForm
*/
WM_HWIN CreateSDR_MainForm(void);
WM_HWIN CreateSDR_MainForm(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
